@startuml "Model_Classes"

class Keyboard {
  -id: int
  -name: String
  -price: double
  -quantity: int
  +Keyboard(id: int, name: String, price: double, quantity: int)
  +getId(): int
  +setName(name: String): void
  +getName(): String
  +setPrice(price: double): void
  +getRole(): double
  +setQuantity(quantity: int): void
  +getQuantity(): int
}

class User {
  -id: int
  -name: String
  -role: int
  -cart: List<Integer>
  +User(id: int, name: String, role: int)
  +getId(): int
  +setName(name: String): void
  +getName(): String
  +setRole(role: int): void
  +getRole(): int
  +getCart(): List<Keyboard>
  +addToCart(item: Keyboard): void
  +removeFromCart(item: Keyboard): void
}
