import { KeyOrientation, KeySize } from "./key-cap";
import { KeyboardLayout } from "./keyboard-layout";

export const SixtyLayout: KeyboardLayout = {
  typingKeys: [
    [ 
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '~', bottomLabel: '`' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '!', bottomLabel: '1' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '@', bottomLabel: '2' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '#', bottomLabel: '3' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '$', bottomLabel: '4' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '%', bottomLabel: '5' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '^', bottomLabel: '6' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '&', bottomLabel: '7' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '*', bottomLabel: '8' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '(', bottomLabel: '9' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: ')', bottomLabel: '0' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '_', bottomLabel: '-' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '+', bottomLabel: '=' },
      { size: KeySize.TWO_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Backspace' },
    ],
    [ 
      { size: KeySize.ONE_POINT_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Tab' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Q' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'W' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'E' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'R' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'T' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Y' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'U' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'I' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'O' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'P' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '{', bottomLabel: '[' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '}', bottomLabel: ']' },
      { size: KeySize.ONE_POINT_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '|', bottomLabel: '\\' },
    ],
    [ 
      { size: KeySize.ONE_POINT_SEVEN_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Caps Lock' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'A' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'S' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'D' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'F' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'G' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'H' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'J' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'K' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'L' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: ':', bottomLabel: ';' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '"', bottomLabel: '\'' },
      { size: KeySize.TWO_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Enter' },
    ],
    [ 
      { size: KeySize.TWO_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Shift' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Z' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'X' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'C' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'V' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'B' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'N' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'M' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '<', bottomLabel: ',' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '>', bottomLabel: '.' },
      { size: KeySize.ONE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: '?', bottomLabel: '/' },
      { size: KeySize.TWO_POINT_SEVEN_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Shift' },
    ],
    [ 
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Ctrl' },
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Win' },
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Alt' },
      { size: KeySize.SIX_POINT_TWO_FIZE_U, orientation: KeyOrientation.HORIZONTAL }, 
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Alt' },
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Win' },
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Menu' },
      { size: KeySize.ONE_POINT_TWO_FIVE_U, orientation: KeyOrientation.HORIZONTAL, topLabel: 'Ctrl' },
    ],
  ]
};